[package]
name = "chord-site"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
ratatui = "0.29.0"
reqwest = { version = "0.12.22", features = ["blocking", "rustls-tls"] }
scraper = "0.23.1"
tokio = { version = "1.46.1", features = ["full"] }
